# vim: ts=2:sw=2:sts=2:et:ft=yaml
# -*- mode: yaml; yaml-indent-offset: 2; indent-tabs-mode: nil; -*-
---

namespace: o0_o
name: 'windows'
version: 0.1.0
readme: README.md
authors:
  - oØ.o (@o0-o)
description: >
  Windows utilities and action plugin base classes for Ansible.
license: GPL-3.0-or-later
tags:
  - collection
  - 'windows'
dependencies:
  o0_o.utils: '>=2.0.0'
repository: 'https://github.com/o0-o/ansible-collection-windows'
issues: 'https://github.com/o0-o/ansible-collection-windows/issues'
build_ignore:
  - .git
  - .github
  - .venv
  - .direnv
  - .wip
  - .pytest_cache
  - .mypy_cache
  - tests/output
  - __pycache__
